package algorithms.imageProcessing;

/**
 *
 * @author nichole
 */
public enum PARAM {
    
    CONTRAST,
    ABSOLUTE_CONTRAST,
    ABSOLUTE_DIFF_BLUE_OR_RED,
    STDEV_CONTRAST,
    STDEV_BLUE_OR_RED,
    DIFF_CIEX,
    DIFF_CIEY,
    STDEV_CIEX,
    STDEV_CIEY,
    INT_ONE,
    RED, GREEN, BLUE,
    R_DIV_TOT, G_DIV_TOT, B_DIV_TOT,
    DIFF_R_DIV_TOT_ONE_THIRD, 
    DIFF_G_DIV_TOT_ONE_THIRD, 
    DIFF_B_DIV_TOT_ONE_THIRD

    /*ABSOLUTE_BLUE_OR_RED,
     ABSOLUTE_DIFF_HUE,
     ABSOLUTE_DIFF_CIEX,
     ABSOLUTE_DIFF_CIEY,
     CONTRAST,
     BLUE_OR_RED,
     HUE,
     CIEX,
     CIEY,
     DIFF_BLUE_OR_RED,
     DIFF_HUE,
     STDEV_HUE,*/
}
